### PR TITLE
Use plone.recipe.zope2instance==6.13.0

### PR DESCRIPTION
**Pull request by reinhardt**
Is there a nicer way to override an individual entry in config/constraints.txt?

It's possible to specify the pip flag `-c` multiple times, but apparently it's only additive. If the constraints files conflict, you get an error.

I think mxdev can override constraints, but IIRC it just reads constraints files, processes them and writes new ones.

### CODE REVIEW

**Comment by thet** [comment]
@reinhardt yes, that's what's mxdev does. I've been told that `uv` supports overriding constraints.

**Review by thet — APPROVED** [review]

**Comment by reinhardt** [comment]
I'm still not quite happy with this PR. For one thing I expect that I'll forget removing that line once the package is pinned to a newer version in the constraints. I considered changing the spec to plone.recipe.zope2instance>=6.13.0, but that would cause it to be upgraded once a new version is released, not once the constraints are updated to that newer version.

I don't know. I'll sleep on it.

**Comment by reinhardt** [comment]
How about this? We only install 6.13.0 if 6.12.2 is currently installed.

```
./py3/bin/pip list | grep "plone.recipe.zope2instance.*6.12.2$" && ./py3/bin/pip3 install plone.recipe.zope2instance==6.13.0
```

Or am I overthinking this?

**Review by thet — APPROVED** [review]
Looks OK to me.

Actually, I'm already hooked on mxdev and think we should introduce that to our stack at some point.
But that's not the topic here :)

**Pull request merged**
